import polars as pl

from onsides import stringsearch
from onsides.predict import predict
from onsides.types import IndexedText
from onsides.stringsearch import MatchContext

langs = ["english", "japanese"]

NETWORK_PATH = Path(config.get(
    "network_path",
    "models/microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract",
))
WEIGHTS_PATH = Path(config.get(
    "weights_path",
    "models/bestepoch-bydrug-PMB_14-ALL-125-all_222_24_25_1e-06_256_32.pth",
))


rule all:
    input:
        expand("_onsides/vocab/meddra_{language}.parquet", language=langs),
        expand("_onsides/combined/label_{language}_preds.parquet", language=["english"]),
        "_onsides/combined/label_japanese_string_match.parquet",
        "_onsides/vocab/meddra_jp_to_eng.parquet",
        # expand("_onsides/combined/label_{language}_preds.parquet", language=langs)


rule build_vocabulary:
    input:
        queries = "snakemake/onsides/evaluate/meddra_vocabs.sql",
        mrconso = "data/MRCONSO.RRF"
    output:
        expand(
            "_onsides/vocab/meddra_{language}.parquet",
            language=langs
        )
    log: "log/evaluate/build_vocabulary.log"
    shell: "duckdb duck.db < {input.queries} 2>&1 | tee {log}"


rule build_labels:
    input:
        us = "_onsides/us/label_text.parquet",
        uk = "_onsides/uk/label_text.parquet",
        eu = "_onsides/eu/label_text.parquet",
        jp = "_onsides/jp/med_label_text.parquet",
        queries = "snakemake/onsides/evaluate/format_labels.sql",
    output:
        "_onsides/combined/english_labels.parquet",
        "_onsides/combined/japanese_labels.parquet",
    log: "log/evaluate/build_labels.log"
    shell: "duckdb < {input.queries} 2>&1 | tee {log}"


rule string_match:
    input:
        labels = "_onsides/combined/{language}_labels.parquet",
        vocabulary = "_onsides/vocab/meddra_{language}.parquet",
    output: "_onsides/combined/label_{language}_string_match.parquet"
    log: "log/evaluate/string_match_{language}.log"
    run:
        with open(log[0], "w") as logfile:
            def log_print(msg):
                print(msg)
                logfile.write(msg + "\n")

            # Load the labels themselves
            raw_labels = pl.read_parquet(input.labels).to_dicts()
            labels = [IndexedText.model_validate(x) for x in raw_labels]
            log_print(f"Found {len(labels)} labels")

            # Load the vocabularies (which we are trying to match)
            raw_terms = pl.read_parquet(input.vocabulary).to_dicts()
            terms = [IndexedText.model_validate(x) for x in raw_terms]
            log_print(f"Matching {len(terms)} terms")

            # Find exact string matches
            matches = stringsearch.parse_texts(texts=labels, terms=terms)
            log_print(f"Found {len(matches)} string matches")
            pl.DataFrame(matches).write_parquet(output[0])


rule evaluate_onsides:
    input: "_onsides/combined/label_{language}_string_match.parquet"
    output: "_onsides/combined/label_{language}_preds.parquet"
    log: "log/evaluate/evaluate_onsides_{language}.log"
    resources: jobs=1
    run:
        with open(log[0], "w") as logfile:
            def log_print(msg):
                print(msg)
                logfile.write(msg + "\n")

            raw_matches = pl.read_parquet(input[0]).to_dicts()
            matches = [MatchContext.model_validate(x) for x in raw_matches]
            log_print(f"Found {len(matches)} raw matches")

            # Apply the BERT model to evaluate the matches in their contexts
            match_texts = [m.context for m in matches]
            predictions = predict(
                texts=match_texts,
                network_path=NETWORK_PATH,
                weights_path=WEIGHTS_PATH,
                text_settings=None,
                batch_size=1_000,
            )
            result = pl.concat([
                pl.DataFrame(matches),
                pl.DataFrame(predictions, schema=["pred0", "pred1"])
            ], how="horizontal")
            result.write_parquet(output[0])
            log_print(f"Wrote {len(result)} predictions to {output[0]}")


rule create_jp_to_eng_meddra_map:
    input:
        mrconso = "data/MRCONSO.RRF",
        queries = "snakemake/onsides/evaluate/meddra_jp_to_eng.sql",
    output:
        "_onsides/vocab/meddra_jp_to_eng.parquet"
    log: "log/evaluate/jp_to_eng_meddra_map.log"
    shell:
        "duckdb < {input.queries} 2>&1 | tee {log}"
